# This is an example of a feature-complete JobFunnel configuration YAML.
# Try this out by simply running: "funnel load -s demo/settings.yaml"

# Path where your master CSV, block-lists, and cache data will be stored
# NOTE: we create any missing directories in these filepaths
master_csv_file: demo_job_search_results/demo_search.csv
cache_folder: demo_job_search_results/cache
block_list_file: demo_job_search_results/demo_block_list.json
duplicates_list_file: demo_job_search_results/demo_duplicates_list.json
log_file: demo_job_search_results/log.log

# Job search configuration
search:
  # Locale settings, one of USA_ENGLISH, CANADA_ENGLISH, CANADA_FRENCH:
  # This tells JobFunnel where the website we are scraping is located, and
  # what language the contents are in.
  locale: GERMANY_GERMAN

  # Job providers which we will search, one of INDEED, MONSTER, GLASSDOOR:
  # NOTE: we choose domain via locale (i.e. CANADA_ENGLISH -> www.indeed.ca)
  # FIXME: we need to add back GLASSDOOR when that's working again.
  providers:
    - INDEED

  # Region that we are searching for jobs within:
  province_or_state: "" # Not used for the german scraper.
  city: "Berlin" # NOTE: this is the full city / town name.
  radius: 0 # km (NOTE: if we were in locale: USA_ENGLISH it's in miles)

  # These are the terms you would be typing into the website's search field:
  keywords:
    - Python
    - Senior
    - AI

  # Don't return any listings older than this:
  max_listing_days: 10

  # Blocked company names that will never appear in any results:
  company_block_list:
    - "EvilCorp"

  # The desired level of work-remoteness (i.e. IN_PERSON, FULLY_REMOTE, ANY,
  # TEMPORARILY_REMOTE, PARTIALLY_REMOTE)
  remoteness: ANY

# Logging level options are: critical, error, warning, info, debug, notset
log_level: INFO

# Delaying algorithm configuration
delay:
  # Functions used for delaying algorithm: CONSTANT, LINEAR, SIGMOID
  algorithm: LINEAR
  # Maximum delay/upper bound for converging random delay
  max_duration: 5.0
  # Minimum delay/lower bound for random delay
  min_duration: 1.0
  # Random delay
  random: True
  # Converging random delay, only used if 'random' is set to True
  converging: False
# # Proxy settings
# proxy:
#   protocol: https  # NOTE: you can also set to 'http'
#   ip: "1.1.1.1"
#   port: 200
